apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-application
  namespace: argocd
spec:
  project: example-projekt
  source:
    repoURL: https://github.com/marcolindner/example-k8s-application.git
    targetRevision: HEAD
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: default
